### ISSUE TITLE
Exception Error in telegramNotifier.py

### ISSUE THREAD

**Issue by pzobrist** [pattertj/LoopTrader#34]
**Describe the bug**
Getting an Exception Error when running main.py when it gets to line 35 of telegramNotifier.py  

Error as follows:

__init__() missing 1 required positional argument: 'update_queue'

I'm running Python 3.9 on a Windows 10 device using Visual Studio Code to debug and have python_telegram_bot==13.5 installed.

**Comment by pattertj** [comment]
Thanks, I just saw this today as well. I think the upgrade in issue #33 impacted this. I will get a fix in soon for this.

**Comment by pattertj** [comment]
Well this fixed the compile, but I am seeing issues with bot commands now. I'll need to triage further.

**Comment by pattertj** [comment]
Alright, should be working now!
