### ISSUE TITLE
400 Error Bad Request: Input Date is not Acceptable When Running Bot After Hours

### ISSUE THREAD

**Issue by pzobrist** [pattertj/LoopTrader#38]
**Describe the bug**

"status":400,"error":"Bad Request","message":"Input date is not acceptable.","path":"/markethours-v1/markets/"}

###################
###################

File "C:\Users\philz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\td\client.py", line 617, in _make_request
    raise NotNulError(message=response.text)
td.exceptions.NotNulError: {"timestamp":"2021-05-07","status":400,"error":"Bad Request","message":"Input date is not acceptable.","path":"/markethours-v1/markets/"}
ERROR - Failed to get market hours, exiting and retrying.
ERROR - Failed to get market hours for ['OPTION'] on 2021-05-06 23:08:22.796997.
Traceback (most recent call last):
  File "C:\Users\Public\LoopTrader-main\BaseTypes\Broker\tdaBroker.py", line 303, in get_market_hours
    hours = self.getsession().get_market_hours(markets=markets, date=str(request.datetime))
  File "C:\Users\philz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\td\client.py", line 980, in get_market_hours
    return self._make_request(method='get', endpoint=endpoint, params=params)
  File "C:\Users\philz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\td\client.py", line 617, in _make_request
    raise NotNulError(message=response.text)
td.exceptions.NotNulError: {"timestamp":"2021-05-07","status":400,"error":"Bad Request","message":"Input date is not acceptable.","path":"/markethours-v1/markets/"}
ERROR - Failed to get market hours, exiting and retrying.

**To Reproduce**

1) Launch main.py via Visual Studio Code / monitor output
2)  The above output was generated when running the bot at 11:08 PM Pacific Time
[autotrader.log](https://github.com/pattertj/LoopTrader/files/6439423/autotrader.log)

**Expected behavior**

Telegram reports the bot has started and I can pull balances and orders no problem.  

**Screenshots**

**Desktop (please complete the following information):**

Windows 10

**Comment by pattertj** [comment]
Alright, main should reflect changes for this now. I reworked the market hours logic as it worked fine if you started during market hours, but starting after-hours would fail as you noted.

Now the logic always searches out the next day with valid hours, starting with today. I then added an extra check that if the next hours are not today, wait for then and skip all other logic.

This should still let us hit the after hours logic the day of an open market, but go to sleep and wait on the weekends.

Thanks for the feedback!!
