### ISSUE TITLE
getenv does not work on a mac

### ISSUE THREAD

**Issue by dataartisan** [pattertj/LoopTrader#70]
**Describe the bug**
On MacOS, configured .env file, tried multiple permissions for the .env file, and ran it from shell as well as under virtual environment. It indicates that it is still not able to read the variables from the .env file.

**To Reproduce**
Create a sample .env file on MacOS and run the scripts as described on the documentation.

**Expected behavior**
OS independent way of reading .env files.

**Desktop (please complete the following information):**
 - OS: MacOS

**Fix**
Add the dependency for dotenv on the pip file.
from dotenv import load_env
load_dotenv()

**Comment by pattertj** [comment]
Thanks for this. I've merged this change into the main code. It runs locally, but I don't have a mac to confirm. Please let me know if this has any issues for you.
