### ISSUE TITLE
Credential file not generated

### ISSUE THREAD

**Issue by dataartisan** [pattertj/LoopTrader#72]
**Describe the bug**
Credential file does not generate. Most likely will not refresh after expiration. Running the application does not prompt the OATH authentication.

**To Reproduce**
Start the app.
{'credential_path': '/Users/s_pant/Desktop/backupmeup/autotrader/LoopTrader/td_session.json',
 'message': 'The credential file does not contain expiration times for your '
            'tokens, please go through the oAuth process.'}
{'credential_path': '/Users/s_pant/Desktop/backupmeup/autotrader/LoopTrader/td_session.json',
 'message': 'The credential file does not contain expiration times for your '
            'tokens, please go through the oAuth process.'}
{'credential_path': '/Users/s_pant/Desktop/backupmeup/autotrader/LoopTrader/td_session.json',
 'message': 'The credential file does not contain expiration times for your '
            'tokens, please go through the oAuth process.'}
{'credential_path': '/Users/s_pant/Desktop/backupmeup/autotrader/LoopTrader/td_session.json',
 'message': 'The credential file does not contain expiration times for your '
            'tokens, please go through the oAuth process.'}

**Expected behavior**
A login oath authentication prompt from which the credential file would be populated.

Credential path in .env is as follows:
CREDENTIALS_PATH= "/Users/s_pant/Desktop/backupmeup/autotrader/LoopTrader/td_session.json"

When this file is generated using the API (by writing the sample app), the app works.

**Comment by pattertj** [comment]
I am not going to add automation for the TDA credential file at this time. Instead, I have revised the documentation on how to do this outside of LoopTrader.
